settings:
  title: 'Status Page'
  url: 'https://status-page.complianceonline.co.za' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: www-complianceonline-co-za
    name: www.complianceonline.co.za
    description: 'Compliance Online website.'
    url: 'https://www.complianceonline.co.za'
    method: GET
    expectStatus: 200

  - id: ello
    name: ELLO - Everyone Love Learning Online
    url: 'https://ello.complianceonline.co.za/'
    method: GET
    expectStatus: 200

  - id: policy-passport
    name: Policy Passport
    url: 'https://admin.policypassport.com/'
    method: GET
    expectStatus: 200